In [1]:
"""
ejemplos de vectores y matrices en python
"""

import numpy as np

vector_nulo = np.zeros(3)
print(f"vector nulo en r3 {vector_nulo}")

[0. 0. 0.]


In [2]:
# Vector original (por ejemplo, [3, 4])
vector_original = np.array([3, 4])

# 1. Calcular la magnitud (norma L2)
magnitud = np.linalg.norm(vector_original)

# 2. Vector unitario: vector / magnitud
vector_unitario = vector_original / magnitud

print("Vector Unitario:")
print(vector_unitario)
# [0.6 0.8]

# Comprobación de que la magnitud es 1
print(f"Magnitud del vector unitario: {np.linalg.norm(vector_unitario)}")
# Magnitud del vector unitario: 1.0

Vector Unitario:
[0.6 0.8]
Magnitud del vector unitario: 1.0


In [3]:
# Matriz cuadrada de 3x3
matriz_cuadrada = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matriz Cuadrada (3x3):")
print(matriz_cuadrada)

Matriz Cuadrada (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
elementos_diagonal = np.array([5, 0, -2])
matriz_diagonal = np.diag(elementos_diagonal)

print("Matriz Diagonal:")
print(matriz_diagonal)
# [[ 5  0  0]
#  [ 0  0  0]
#  [ 0  0 -2]]

Matriz Diagonal:
[[ 5  0  0]
 [ 0  0  0]
 [ 0  0 -2]]


In [5]:
# Matriz Identidad de 4x4
matriz_identidad = np.eye(4)

print("Matriz Identidad (4x4):")
print(matriz_identidad)
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]

Matriz Identidad (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
# Matriz Simétrica (el elemento [0, 1] es igual al [1, 0], etc.)
matriz_simetrica = np.array([
    [10, 5, 8],
    [5, 20, -3],
    [8, -3, 30]
])

# Comprobar la simetría comparándola con su transpuesta (A == A.T)
es_simetrica = np.array_equal(matriz_simetrica, matriz_simetrica.T)

print("Matriz Simétrica:")
print(matriz_simetrica)
print(f"¿Es igual a su transpuesta? {es_simetrica}")
# ¿Es igual a su transpuesta? True

Matriz Simétrica:
[[10  5  8]
 [ 5 20 -3]
 [ 8 -3 30]]
¿Es igual a su transpuesta? True
